module FindDupeImages
  # source http://www.sitepoint.com/web-foundations/mime-types-complete-list/
  IMAGE_MIME_TYPES = %w(
    image/gif
    image/jpeg
    image/pjpeg
    image/png
    image/bmp
    image/tiff
    image/pict
    image/cmu-raster
    image/fif
    image/florian
    image/vnd.fpx
    image/vnd.net-fpx
    image/vnd.rn-realpix
    image/vnd.wap.wbmp
    image/vnd.rn-realflash
    image/vnd.dwg
    image/g3fax
    image/ief
    image/jutvision
    image/vasa
    image/naplps
    image/x-dwg
    image/x-jg
    image/x-niff
    image/x-portable-bitmap
    image/x-pict
    image/x-pcx
    image/x-portable-graymap
    image/x-jps
    image/x-xpixmap
    image/x-portable-anymap
    image/x-portable-pixmap
    image/x-quicktime
    image/x-tiff
    image/x-windows-bmp
    image/x-icon
    image/x-cmu-raster
    image/x-rgb
    image/x-xbitmap
    image/x-xbm
    image/x-xwd
    image/xbm
    image/x-xwindowdump
    application/octet-stream
  )
end
